import { useMemo, useState } from "react";
import { useLab } from "@/lib/labStore";
import { CLUES, RESETS } from "@/lib/missions";

function buildNotes(state: ReturnType<typeof useLab>["state"]): string {
  const date = new Date().toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" });

  const resetLines = RESETS
    .filter((r) => state.resetsUsed[r.key] > 0)
    .map((r) => `  • ${r.title}: ${state.resetsUsed[r.key]}×`)
    .join("\n") || "  • (none logged this session)";

  const clueLines = CLUES
    .filter((c) => state.cluesNoticed[c.key] > 0)
    .map((c) => `  • ${c.label} (noticed ${state.cluesNoticed[c.key]}×)`)
    .join("\n") || "  • (none logged this session)";

  const missionLines = Object.entries(state.missionsSolved)
    .filter(([, n]) => n > 0)
    .map(([id, n]) => `  • ${id}: ${n} challenge${n === 1 ? "" : "s"} solved`)
    .join("\n") || "  • (no missions completed this session)";

  const brainChecks = state.log.filter((l) => l.type === "clue" && l.payload.startsWith("Brain Check:"));
  const brainCheckLines = brainChecks.length > 0
    ? brainChecks.map((l) => `  • ${l.payload}`).join("\n")
    : "  • (no brain checks triggered)";

  const returnEvidence = state.log.filter(
    (l) => l.type === "tiny-step" || l.type === "mission-solved"
  ).length;

  const ref = state.reflection;

  return [
    `Brave Brain Adventure Lab — Session Summary`,
    `Date: ${date}`,
    ``,
    `Session Focus:`,
    `  Catching stuck feelings early, using resets, and returning to task.`,
    ``,
    `Resets Used:`,
    resetLines,
    ``,
    `Body Clues Noticed (self-reported):`,
    clueLines,
    ``,
    `Mid-Mission Brain Checks:`,
    brainCheckLines,
    ``,
    `Missions Engaged:`,
    missionLines,
    ``,
    `Evidence of Returning to Task:`,
    `  • Returned to task after stuck moments: ${returnEvidence} time${returnEvidence === 1 ? "" : "s"}`,
    `  • Brave Brain Meter ended at ${state.braveBrain}/100`,
    `  • Badges earned: ${state.badges.join(", ") || "none yet"}`,
    `  • Stuck Zone Boss completed: ${state.bossDone ? "Yes 🏆" : "Not yet"}`,
    ``,
    `Student Reflection:`,
    `  • Something hard: ${ref.hard || "(not entered)"}`,
    `  • Body clue noticed: ${ref.clue || "(not entered)"}`,
    `  • Reset used: ${ref.reset || "(not entered)"}`,
    `  • How they came back: ${ref.comeback || "(not entered)"}`,
    `  • Brave Brain self-rating: ${ref.stars}/5`,
    ``,
    `Suggested Next Session Focus:`,
    `  • Keep noticing body clues early — celebrate the catch, not just the solve.`,
    `  • Continue practicing one chosen reset until it becomes automatic.`,
    `  • Add a "one tiny step" rehearsal at the start of harder missions.`,
    ``,
    `— Generated by Brave Brain Adventure Lab`,
  ].join("\n");
}

export function CoachNotes() {
  const { state, reset } = useLab();
  const [tick, setTick] = useState(0);
  const [copied, setCopied] = useState(false);
  const notes = useMemo(() => buildNotes(state), [state, tick]);

  async function copy() {
    try {
      await navigator.clipboard.writeText(notes);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch { /* noop */ }
  }

  return (
    <div className="space-y-5">
      <header className="pop-card p-6">
        <h1 className="text-3xl font-extrabold">📝 Coach Notes</h1>
        <p className="text-muted-foreground mt-1">
          A plain-text summary of today's session. Copy and paste into an email or your notes app.
        </p>
      </header>

      <div className="pop-card p-6">
        <div className="flex flex-wrap gap-2 mb-4">
          <button
            onClick={() => setTick((t) => t + 1)}
            className="px-4 py-2 rounded-full bg-primary text-primary-foreground font-bold hover:opacity-90"
          >
            🔄 Refresh notes
          </button>
          <button
            onClick={copy}
            className="px-4 py-2 rounded-full bg-card border-2 border-border font-bold hover:border-primary/40"
          >
            {copied ? "✅ Copied!" : "📋 Copy to clipboard"}
          </button>
          <button
            onClick={() => {
              if (confirm("Start a fresh session? This clears today's progress.")) reset();
            }}
            className="px-4 py-2 rounded-full bg-card border-2 border-border font-bold text-destructive hover:border-destructive/40 ml-auto"
          >
            🧹 Clear session
          </button>
        </div>

        <pre className="whitespace-pre-wrap text-sm bg-secondary/60 border-2 border-border rounded-2xl p-5 font-mono leading-relaxed">
{notes}
        </pre>
      </div>
    </div>
  );
}
